import { Inter} from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import Header from "@/components/Header";
import { ClerkProvider } from "@clerk/nextjs";

export const inter = Inter({
  subsets:["latin"]
})

export const metadata = {
  title: "CareerAI🔥",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>

    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.className}`}
      >
         <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <Header/>
            <main className="min-h-screen">
            {children}
              <footer className="bg-muted/50 py-12">
                <div className="container mx-auto px-4 text-center text-gray-200">
        <p>Made By Vikram D P</p>
                </div>
              </footer>
            </main>
          </ThemeProvider>
      </body>
    </html>
    </ClerkProvider>

  );
}
